name: Run Tests with Coverage and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.3'
    
    - name: Install dependencies
      run: go mod tidy

    - name: Run service tests
      run: |
        go test -coverprofile=coverage_handler.out ./handler/...
        go test -coverprofile=coverage_service.out ./service/...

    - name: Generate coverage report
      run: |
        go tool cover -func=coverage_handler.out
        go tool cover -func=coverage_service.out